### ISSUE TITLE
Returning Rental Bike - Money Returned, Bike Persists

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#15] opened 2022-03-24 18:11 UTC
<h2>What bug have you found?</h2>

Rent a bike, return and get your money, but the bike is still there.

<h2>What do you expect should happen?</h2>

Gimme my money, take my bike. Don't leave me a free bike.

<h2>Anything to support your bug report?</h2>

(https://medal.tv/games/gta-v/clips/e4ApXHvCX2Xky/d1337kQnoVhV?invite=cr-MSx2dnosMjYzNTY1MDUs)

@ghost

**Comment by amirradman** [comment] 2022-03-28 08:15
Have been unable to reproduce this issue. Tested multiple bike rental locations with various bikes. Able to successfully return the bike and receive the deposit. Closing

**Closed by amirradman** 2022-03-28 08:15 UTC
Labels: bug
